Repository McNaBry/orbital-grindtogether, pull requests merged in 2023-05, with the labels that each got.

#5 Modifications to original next.js app and addition of About page
  app/about/about.css
  app/about/page.tsx
  app/globals.css
  app/page.module.css
  app/page.tsx
  package-lock.json
  package.json
  public/images/bootstrap-logo.png
  public/images/firebase-logo.png
  public/images/html5-logo.png
  public/images/motivation-pic.png
  public/images/netlify-logo.png
  public/images/nodejs-logo.png
  public/images/react-logo.png
  public/images/study-together.png
Labels: feature

#6 Add sign-up page feature
  app/about/about.css
  app/globals.css
  app/layout.tsx
  app/page.tsx
  app/sign-in/signin.css
  app/sign-up/EyeForPassword.tsx
  app/sign-up/Password.tsx
  app/sign-up/PasswordChecks.js
  app/sign-up/page.tsx
  app/sign-up/signup.css
  package-lock.json
  package.json
  public/images/aesthetic-library.png
  public/images/danger.svg
  public/images/success.svg
Labels: feature

#12 Sign up page
  app/sign-up/eyeForPassword.tsx
  app/sign-up/page.tsx
  app/sign-up/password.tsx
  app/sign-up/passwordChecks.js
  app/sign-up/signup.css
Labels: bug, feature

#13 Study invitation page
  app/globals.css
  app/layout.tsx
  app/study-listings/data.tsx
  app/study-listings/filterPanel.tsx
  app/study-listings/page.tsx
  app/study-listings/studyListings.css
  app/study-listings/studyListings.tsx
  package-lock.json
  package.json
  public/images/terrace_pic.png
Labels: feature

#9 Add sign-in page feature
  app/page.tsx
  app/sign-in/page.tsx
  app/sign-in/signin.css
  app/sign-up/email.tsx
  app/sign-up/page.tsx
  app/sign-up/signup.css
  package-lock.json
  package.json
  public/images/study-aesthetic.png
Labels: feature

#15 Added a starter page to link to sign in and sign up
  app/globals.css
  app/page.tsx
  app/start.css
Labels: feature

#18 sign-in and sign-up code refactor and redesign of sign-in
  app/(authentication)/auth.module.css
  app/(authentication)/email.tsx
  app/(authentication)/eyeForPassword.tsx
  app/(authentication)/password.tsx
  app/(authentication)/sign-in/page.tsx
  app/(authentication)/sign-in/signin.css
  app/(authentication)/sign-up/page.tsx
  app/(authentication)/sign-up/passwordChecks.js
Labels: feature

#17 Add profile page feature
  app/profile-page/editButton.tsx
  app/profile-page/editableCard.tsx
  app/profile-page/nonEditableCard.tsx
  app/profile-page/page.tsx
  app/profile-page/profilepage.css
  app/profile-page/ratingCard.tsx
  app/profile-page/saveChanges.tsx
Labels: feature

#29 Create README.md
  README.md
Labels: documentation
